### ISSUE TITLE
What are the ways to deploy this project

### ISSUE THREAD

**Issue by opensourcegeek** [antimonyproject/antimony-core#1]
This project looks super interesting. I've just seen the talk in Rust Fest, I'm curious to know how to deploy my code (my implementations of bolt/spouts) when using this project. I'd really like to take it for a spin but currently I'm not completely sure how to deploy it though. Also, are you planning to support this project?

**Comment by msmakhlouf** [comment]
Hello @opensourcegeek,

We are working on documenting the process for deploying the antimony on Apache Mesos for a multinode cluster as well as documenting/finishing up some code to allow for single host / local deployment.

In all cases, you would need the antimony-cli tool which would allow you to submit your topology to a cluster, we are going to opensource that shortly.

As for supporting the project yes we intend to actively support the project and would be very glad to welcome contributors to join us. we just published a contributing guide here on GitHub and set up a gitter channel [gitter.im](https://gitter.im/antimony-rs) for discussing the roadmap moving forward with this project.

Many Thanks & Kind Regards
Mohammed

**Comment by opensourcegeek** [comment]
Thanks for getting back @msmakhlouf - I'm looking forward to it!

**Comment by msmakhlouf** [comment]
Closing the issue. Docs will be uploaded shortly. Thank you
